# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52209590492b028a431635aab42aaa9b1b39f972dc382d58a9e50c65e6d320ca6cadf3946b1735ab558dc5d01710831a0c6a77b80aeaaeaa2e060a50e33637fb

test:
  secret_key_base: fddaf61322fccc5d4a2ea0014228120c7147027a14ee4209e003f6f1b9e453287843728ba8c27470de0f0ebabd8218c01a7533b2b6b0bbde7fdeea4179ddb68a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
